Законченная реализация таблицы с использование Bootstrap
VolffS/Bootstrap pull request #2
Opened 2024-02-15 01:05 UTC by VolffS

Код рабочий. Предложения, замечания по семантике или реализации?

2024-02-15 09:20 UTC, xDSUP requested changes

2024-02-15 09:20 UTC, xDSUP commented on script.js
> +let selectRow = [];
массивы и обьекты в которы лежит несколько чего-то принято называть во мн числе, чтобы не путать читающего код)  
относится тут к большинству переменных

2024-02-15 09:20 UTC, xDSUP commented on script.js
> +        // creatRowInTable(idRow,`${arrRowElement.firstName} ${arrRowElement.lastName}`,arrRowElement.email,
а коммент зач оставил?

2024-02-15 09:20 UTC, xDSUP commented on script.js
> +function addSelectRow(element) {
Кажется, что эту штуку можно упростить. Зачем хранить целую строку, если нам оттуда по факту нужен её айдишник, который делает её уникальной. По нему и найти и  удалить можно)

2024-02-15 09:20 UTC, xDSUP commented on script.js
> +          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
иконки = крута)

вот эти <path> внутри svg можно не таскать везде, выглядит оч жутко.

для этого можно сделать одну svg в index.html где сделать <symbol> 

```
 <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
      <symbol id="add" viewBox="0 0 19 20">
        <!-- Generator: Sketch 52.2 (67145) - http://www.bohemiancoding.com/sketch -->
        <title>+</title>
        <desc>Created with Sketch.</desc>
        <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
          <polygon id="+" fill="#EEE5B5" points="10.777832 11.2880859 10.777832 19.5527344 8.41650391 19.5527344 8.41650391 11.2880859 0.627929688 11.2880859 0.627929688 8.92675781 8.41650391 8.92675781 8.41650391 0.662109375 10.777832 0.662109375 10.777832 8.92675781 18.5664062 8.92675781 18.5664062 11.2880859" />
        </g>
      </symbol>
      <symbol id="unmute" viewBox="0 0 36 36">
        <path class="ytp-svg-fill ytp-svg-volume-animation-speaker" clip-path="url(#ytp-svg-volume-animation-mask)" d="M8,21 L12,21 L17,26 L17,10 L12,15 L8,15 L8,21 Z M19,14 L19,22 C20.48,21.32 21.5,19.77 21.5,18 C21.5,16.26 20.48,14.74 19,14 ZM19,11.29 C21.89,12.15 24,14.83 24,18 C24,21.17 21.89,23.85 19,24.71 L19,26.77 C23.01,25.86 26,22.28 26,18 C26,13.72 23.01,10.14 19,9.23 L19,11.29 Z" fill="#fff" id="ytp-id-15"></path>
      </symbol>
</svg>
```

а использовать в других местах можно вот так: 
```
            <svg viewBox="0 0 27 27" width="27" height="27">
              <use xlink:href="#unmute"></use>
            </svg>
```

2024-02-15 09:20 UTC, xDSUP commented on script.js
> +    deleteRow();
если функция удаляет несколько строк, то пусть уже во мн числе будет) 
и в целом, плохая практика, когда функция внутри чет побочное ещё делает. Конкретна эта сейчас чистит массив и обновляет табличку)

Должно быть чет типо такого, так мы побочных меньше делаем внутри)
```
datatable = deleteRows(selectRows, datatable);
refreshTable(dataTable);
```
+ давай почитаем про "чистые функции" и попробуем не работать с глобальными переменными настолько много

2024-02-15 09:20 UTC, xDSUP commented on script.js
> +function deleteRow() {
там еще моментик, я отфильтровал по статусу и удалил пару строк, а у меня фильтр слетел, не юзер френдли получается

2024-02-15 09:20 UTC, xDSUP commented on script.js
> +                    <div class="mb-1 form-floating">
смело выноси тоже в отдельную функцию генерации инпута по шаблонной строке. 
чтобы в итоге тут было что-то типо.
```
${createInput('first-name', 'Имя', dataTable[elementRow.id].firstName)}
${createInput('last-name', 'Фамилия', dataTable[elementRow.id].lastName)}
```

дальше тоже поправь, такую стену очень тяжело просматривать

2024-02-15 09:20 UTC, xDSUP commented on script.js
> +                    return element.firstName.toLowerCase().includes(requiredValue.toLowerCase()) ||
`requiredValue.toLowerCase()` - если что-то встречается больше одного раза - стоит задуматься над тем, чтобы вынести это в переменную)

2024-02-15 09:20 UTC, xDSUP commented on script.js
> +        if (sortSelectStatus !== "") {
ты сделал крутую штуку с фильтром по статусу(так что переименуй в фильтр) Но это немного не сортировка. 
Сортировка эт когда они по порядку выстраиваются. 
Эту фичу я предлагаю не трогать, а сортировку давай запилим на поле имени кандидата. Чтобы по клику на заголовок таблицы было 3 режима: 

1. без сортировки
2. сортировка по алфавиту asc (а-я)
3. сортировка по алфавиту desc (я-а)

режимы переключатся последовательно, те из 1 - 2 - 3 - 1 и т.д

2024-02-15 09:23 UTC, xDSUP commented on script.js
> +        row.innerHTML = createCellsTable( `${employees.firstName} ${employees.lastName}`,employees.email,
а давай запилим функцию перерисовки отдельной строки по её id, как вариант)

2024-02-15 09:28 UTC, xDSUP commented on script.js
> +    btnModify.addEventListener("click", (ev)=>{
встречаются дубли вот этих листенеров еще и в инициализации всех селекторов, кажется что их инициализацию можно закинуть в createDocHTMLPattern
если там возвращать не string, а именно элемент

2024-02-15 09:41 UTC, xDSUP commented on script.js
> +    deleteRow();
https://habr.com/ru/companies/ruvds/articles/519654/

2024-02-15 10:34 UTC, VolffS commented on script.js
> +function addSelectRow(element) {
В данной реализации сохранялся объект. Так как в функции удаления использовался querySelector, который не принимал значения начинающиеся на цифру, тем самым мой id становился не валидным значением.
Изменено на усложнённый запрос. 
Done

2024-02-15 10:45 UTC, VolffS commented on script.js
> +          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
done

2024-02-15 12:22 UTC, xDSUP commented on index.html
> +    <!-- Тестовая строка. Удаляется во время обновления таблицы в refreshTable() внутри JS  -->
Есть прежложение дрогнуть её нафиг) вместо нее в теле таблицы должен быть какой-нибудь spinner, чтобы пользователю показать, что что-то происходит.

Или на краний случай надпись : загружается)

2024-02-16 13:57 UTC, VolffS commented on script.js
> +    deleteRow();
done

2024-02-16 13:57 UTC, VolffS commented on script.js
> +function deleteRow() {
done

2024-02-16 13:57 UTC, VolffS commented on script.js
> +                    <div class="mb-1 form-floating">
done

2024-02-16 13:57 UTC, VolffS commented on script.js
> +                    return element.firstName.toLowerCase().includes(requiredValue.toLowerCase()) ||
done

2024-02-16 13:57 UTC, VolffS commented on script.js
> +        if (sortSelectStatus !== "") {
done

2024-02-16 13:57 UTC, VolffS commented on script.js
> +        row.innerHTML = createCellsTable( `${employees.firstName} ${employees.lastName}`,employees.email,
done

2024-02-16 13:57 UTC, VolffS commented on script.js
> +    btnModify.addEventListener("click", (ev)=>{
done

2024-02-16 13:57 UTC, VolffS commented on index.html
> +    <!-- Тестовая строка. Удаляется во время обновления таблицы в refreshTable() внутри JS  -->
done

2024-02-16 13:57 UTC, VolffS commented on index.html
> +    <!-- Тестовая строка. Удаляется во время обновления таблицы в refreshTable() внутри JS  -->
done

2024-02-16 17:11 UTC, RVMZZES commented on index.html
> +
куда пропали опшенсы?

2024-02-16 17:11 UTC, RVMZZES commented on index.html
> +
тоже самое

2024-02-16 17:11 UTC, RVMZZES commented on index.html
> +                        <input type="text" class="form-control " id="first-name" name="firstName" placeholder="" required>
если не планируешь писать значение какого-то атрибута, то не пиши и свойство

2024-02-16 17:11 UTC, RVMZZES commented on index.html
> +<button type="button" class="btn btn-danger" id="delete__Row" >Удаление</button>
касательно всего нейминга:
если используешь где-то в id camelCase, то старайся делать везде также, если через '_', то также везде в других местах делаешь. 
Я увидел все варианты, хотя проект - один)

2024-02-16 17:11 UTC, RVMZZES commented on index.html
> +<button type="button" class="btn btn-danger" id="delete__Row" >Удаление</button>
также это не только id касается, а всего нейминга (папки, классы и т.д.)

2024-02-16 17:11 UTC, RVMZZES commented on index.html
> +<button type="button" class="btn btn-success delete__checkBox" id="deleteCansel">Отменить</button>
cancel

2024-02-16 22:05 UTC, xDSUP commented on index.html
> +
а они из массива генерятся теперь

2024-02-16 22:25 UTC, xDSUP commented on script.js
> +function redrawingFieldById(id, employees) {
не используется

2024-02-16 22:25 UTC, xDSUP commented on script.js
> +function redrawingFieldById(id, employees) {
employees - почему тут мн ч хотя там инфа о одном сотруднике?

2024-02-16 22:28 UTC, xDSUP commented on script.js
> +        row.innerHTML = createCellsTable( `${employees.firstName} ${employees.lastName}`,employees.email,
смотри еще какая тема, вот захотим мы добавить новое поле в таблицу, сколько функций сейчас придется менять?) 

когда параметров больше 3-х уже можно объектом передавать, у тебя таким служит employees

2024-02-16 22:30 UTC, xDSUP commented on script.js
> +        for (const element of arrRow) {
давай arr не будем добавлять в нейминги, как-то криво смотрится. 
пусть будет rows )

2024-02-16 22:31 UTC, xDSUP commented on script.js
> +    if  (arrRow[0].row === undefined) {
шо за костыли)

2024-02-16 22:32 UTC, xDSUP commented on script.js
> +    if  (arrRow[0].row === undefined) {
эта функция должна принимать параметром массив обьектов какого-то одного вида, а не 2-х

2024-02-16 22:37 UTC, xDSUP commented on script.js
> +                let trueField = new Object();
Как по мне проще так)
```
                let trueField = {
                    id: index,
                    row: element
                };
```

2024-02-16 22:41 UTC, xDSUP commented on script.js
> +function findField(dataTable, searchWord, searchStatus, ascendingDescending) {
во-первых по названию функции я понимаю, что мы идем поле(сейчас читается как "найти поле"). Какое поле?)
во-вторых  тут происходит слишком много. Нужно разбить отдельно на фильтрацию записей и сортировку

2024-02-16 22:44 UTC, xDSUP commented on script.js
> +function findField(dataTable, searchWord, searchStatus, ascendingDescending) {
фильтр я бы тоже хранил и передевал уже обьектиком. Примерно таким
```
filter = {
  search: "", // поле поиска наверхку
  statusFilter: "" // фильтр по статусу твой
}
```

2024-02-16 22:53 UTC, xDSUP commented on script.js
> +        let idRow = 0;
а зачем генерить айдишники записям, если они в данных приходят уже?)

2024-02-16 23:01 UTC, xDSUP commented on script.js
> +function creatRowInTable(id, name, email,title,phone,status, position) {
не используется?

2024-02-16 23:04 UTC, xDSUP commented on script.js
> +function creatRowInTable(id, name, email,title,phone,status, position) {
и в ней еще куча функций старых тогда получается)

2024-02-16 23:09 UTC, xDSUP commented on script.js
> +function addSelectOption(arrOption) {
не используется

2024-02-16 23:10 UTC, xDSUP commented on script.js
> +            listOptions += `<option value="${arrOptionElement}" selected>${formatFirstCharUp(arrOptionElement)}</option>`;
иф можно сократить и поместить в конкретное место

`listOptions += `<option value="${arrOptionElement}" >${formatFirstCharUp(arrOptionElement)}</option>`;`

штука называется **тернарный оператор** и означает мини ифчик

2024-02-16 23:44 UTC, xDSUP commented on index.html
>  <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal" >Добавить</button>
Общий коммент. При открытии формы добавления на всех полях сразу горит, что они не валидные, кажется, там можно на событие фокуса или инпута завязаться лучше. Ттак будет юзер френдли, а то открываешь форму и ощущение будто уже что-то плохое натворил

2024-02-17 06:22 UTC, VolffS commented on index.html
> +                        <input type="text" class="form-control " id="first-name" name="firstName" placeholder="" required>
В данном случаи это не моя прихоть, а специфика bootstrap. Без (placeholder="") он некорректно отображается

2024-02-19 14:53 UTC, VolffS commented on script.js
> +function redrawingFieldById(id, employees) {
Буду пытаться имена более осмысленно

2024-02-19 14:54 UTC, VolffS commented on script.js
> +        row.innerHTML = createCellsTable( `${employees.firstName} ${employees.lastName}`,employees.email,
Спасибо за совет буду это учитывать. Done

2024-02-19 14:54 UTC, VolffS commented on script.js
> +        for (const element of arrRow) {
done

2024-02-19 14:55 UTC, VolffS commented on script.js
> +    if  (arrRow[0].row === undefined) {
done

2024-02-19 14:55 UTC, VolffS commented on script.js
> +                let trueField = new Object();
Учту в последующих реализациях. Done

2024-02-19 14:55 UTC, VolffS commented on script.js
> +function findField(dataTable, searchWord, searchStatus, ascendingDescending) {
Done

2024-02-19 14:56 UTC, VolffS commented on script.js
> +        let idRow = 0;
Чтобы пользователи не видели настоящий Id

2024-02-19 14:57 UTC, VolffS commented on script.js
> +function creatRowInTable(id, name, email,title,phone,status, position) {
Жалко их как-то. Функции это наши дети.
Done

2024-02-19 14:59 UTC, VolffS commented on script.js
> +function addSelectOption(arrOption) {
Прошу вас быть немного внимательней. Она используется при создании модальной функции. Ищите её в exampleModal

2024-02-19 15:00 UTC, VolffS commented on script.js
> +            listOptions += `<option value="${arrOptionElement}" selected>${formatFirstCharUp(arrOptionElement)}</option>`;
Не знал что тернарный оператор можно туда поместить. Учту
Done

2024-02-19 15:06 UTC, xDSUP commented on script.js
> +function creatRowInTable(id, name, email,title,phone,status, position) {
![image](https://github.com/VolffS/Bootstrap/assets/24694817/1f3e4c97-1924-4e6a-bc66-7eebf1dfe905)

2024-02-19 15:09 UTC, xDSUP commented on script.js
> +function addSelectOption(arrOption) {
простите

2024-02-19 15:16 UTC, xDSUP commented on script.js
> +    console.log(phone)
Консольлоги не пушим в гит)

2024-02-19 15:17 UTC, xDSUP commented on script.js
> +    console.log(phone)
Options - переменные с маленькой буквы должны называться

2024-02-19 15:23 UTC, VolffS commented on index.html
>  <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal" >Добавить</button>
done

2024-02-19 15:23 UTC, VolffS commented on script.js
> +    console.log(phone)
Done

2024-02-19 15:23 UTC, VolffS commented on script.js
> +    console.log(phone)
Done

2024-02-19 15:29 UTC, VolffS commented on index.html
> +<button type="button" class="btn btn-success delete__checkBox" id="deleteCansel">Отменить</button>
done

2024-02-19 15:31 UTC, VolffS commented on index.html
> +<button type="button" class="btn btn-danger" id="delete__Row" >Удаление</button>
Справедливо мой просчёт. Что касаемо нейминга через '_' , поправил. Что касается иной стилизации в input это необходимость для более удобной работы с данными в js изменений не будет.
Done

2024-02-19 15:32 UTC, xDSUP approved these changes

2024-02-21 06:35 UTC, merged